language: python

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34

python:
    - "2.7"

install:
    - "pip install tox coveralls"

script:
    - tox -e $TOX_ENV

after_success:
    - "coveralls"
